# .pre-commit-config.yaml

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
   - id: end-of-file-fixer
   - id: trailing-whitespace

# isort
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort

# black
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=120
        - --include='\.pyi?$'

        # these folders wont be formatted by black
        - --exclude="""\.git |
          \.__pycache__|
          \.hg|
          \.mypy_cache|
          \.tox|
          \.venv|
          _build|
          buck-out|
          build|
          dist"""

      language_version: python3.8


# pylint
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          --max-line-length=120,
          --fail-under=8,
          --disable=missing-module-docstring,
          --disable=unused-import
        ]
